name: Build em um fluxo

on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - opened

# defaults:
#   run:
#     working-directory: ./ci

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run detekt
      run: ./gradlew detekt

    - name: Run tests
      run: ./gradlew test

    - name: Run build
      run: ./gradlew build
